FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN pip install --no-cache-dir confluent-kafka fastapi "uvicorn[standard]" redis

COPY api.py .

EXPOSE 8000
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
